export const CREATE = 'CREATE'
export const SET = 'SET'
export const LOADING = 'LOADING'
export const ERROR = 'ERROR'
export const DELETE = 'DELETE'
export const UPDATE = 'UPDATE'
export const ID = 'ID'