export const FETCH = 'FETCH'
export const SET_TASKS = 'SET_TASKS'
export const CREATE = 'CREATE'
export const LOADING = 'LOADING'
export const DELETE = 'DELETE'
export const UPDATE = 'UPDATE'
export const ERROR = 'ERROR'